### ISSUE TITLE
Error handling is inconsistent

### ISSUE THREAD

**Issue by zombiezen** [howeyc/gopass#15]
The internal `getch` function has completely different error-handling behavior depending on platform:

* The BSD code ignores the potential error (a -1 return) from the `read()` call, so if it fails, it returns an undefined value, since it reads stack memory.
* The *nix code panics (not ideal)
* I'm not a Windows expert, but it looks like it ignores the errors completely. I'm imagining the return value is zero since Go zeroes the value?

My proposed fix is to make the functions in this package return an `error`.  I know this is a breaking API change.  To maintain compatibility, you could phase this in by adding new functions with the proper behavior and adding a deprecation notice to the docs of the existing functions.  Might I recommend `Read` for the function name, since then callers will use `gopass.Read` instead of `gopass.GetPasswd` (as per [Effective Go](https://golang.org/doc/effective_go.html#package-names))?

**Comment by johnl** [comment]
Hi - this is a welcome change, but I just wanted to let you know it did obviously break the API and broke some code I had that relied on it. It was easily fixed of course, so no real problem, but you might want to consider a way to avoid this in future. I've seen some other projects using different branches for different major versions - I'm not much of an expert on this though, maybe I should be importing it differently?

Hope this doesn't sound too whiny - I just thought I'd let you know in case you weren't aware of the problem :)
