### ISSUE TITLE
Don't use println built-in

### ISSUE THREAD

**Issue by zombiezen** [howeyc/gopass#16]
As per the [spec](https://golang.org/ref/spec#Bootstrapping), `println()` is not guaranteed to be available.  You should use `os.Stdout.Write([]byte{'\n'})` instead.

**Comment by shurcooL** [comment]
Also, `println` by default prints to stderr, so if that's a desired property one wants to maintain, it should be `os.Stderr.Write([]byte{'\n'})`.
