### ISSUE TITLE
Interrupting a programming while calling GetPasswd will not reset terminal mode

### ISSUE THREAD

**Issue by zombiezen** [howeyc/gopass#18]
See https://code.google.com/p/gopass/source/browse/gopass.go for a way of handling this.

**Comment by howeyc** [comment]
Can you tell me how to reproduce such behavior? I haven't been able to do this. I've tried Ctrl+C, kill, I'm not sure how to make this happen.

**Comment by johnSchnake** [comment]
I think this was fixed by https://github.com/howeyc/gopass/blame/master/win.go#L29

**Comment by johnSchnake** [comment]
I believe this was addressed by https://github.com/howeyc/gopass/pull/26 by using the windows MakeRaw from ssh/terminal.  That disables processed input mode like I had suggested above.
