### ISSUE TITLE
GetPasswd signature change breaks other libraries

### ISSUE THREAD

**Issue by mikeatlas** [howeyc/gopass#19]
Hi,

Unfortunately this is one of those situations where package and version management is lacking in the Go ecosystem badly. 

Your recent change to `GetPasswd`'s return signature, which now returns `([]byte, error)` (6da59536bf3a19dc63b9cdd2f92b43d8643682eb in pass.go) breaks a downstream dependent library, `gopkg.in/godo.v2`, which expected only a single return value [(see here)](https://github.com/go-godo/godo/search?utf8=%E2%9C%93&q=getpasswd).

I'd suggest you consider also using gopkg.in and version new changes, and I'll notify the repo/owner of `godo.v2` about the breaking change and cross-reference this issue. They will have to update their code as well, but if you version your changes and pin them with gopkg in the future, downstream packages won't break like they did here.

Thanks,
Mike

**Comment by tectoro** [comment]
+1 Same issue here. This is breaking godo

**Comment by mikeatlas** [comment]
(Side note, `godo` is used by https://github.com/mgutz/logxi and we use logxi, and that's how I ended up here posting this issue)

**Comment by shurcooL** [comment]
> Unfortunately this is one of those situations where package and version management is lacking in the Go ecosystem badly.

FWIW, this is an avoidable situation even without any package/version management.

Before making a breaking API change, one can check the known importers of the package (in this case, they're https://godoc.org/github.com/howeyc/gopass?importers) and take that into account. If it's a few, it's easy to make PRs to those projects to update them. If it's that many, perhaps avoid making breaking API changes at the same import path, or make many PRs in an automated way.

It's not perfect (this will miss any unknown importers and private code, and people can be slow to accept PRs), but it's something.

**Comment by JohnMaguire** [comment]
This hit me too. :( I also would appreciate versioning for gopkg.in support.

**Comment by howeyc** [comment]
No longer maintained.
