### ISSUE TITLE
Delayed terminal restore causes stair-stepping effect

### ISSUE THREAD

**Issue by mgedmin** [howeyc/gopass#32]
Please see https://github.com/github/hub/issues/1262 for the description of the issue, and https://github.com/github/hub/commit/70d7bb66d54c922ef7bdfe59bb26283b7cb8a365#commitcomment-18977708 for the possible root cause, which is in howeyc/gopass/pass.go.

A summary:
- applications that use howeyc/gopass to ask for passwords end up displaying the prompts with a stair-case effect, i.e.
![ekrano nuotrauka is 2016-09-10 18-15-20](https://cloud.githubusercontent.com/assets/159967/18427259/995603a0-78cf-11e6-9721-fc15298fc855.png)
- this is likely caused by pass.go emitting a `\n` *before* it restores the terminal state, which keeps the stty `onlcr` flag unset

**Comment by howeyc** [comment]
Thanks for letting me know.

**Comment by mislav** [comment]
@howeyc Thanks for the quick response!
