### ISSUE TITLE
GetPasswd should accept a Context or offer some way to unblock it

### ISSUE THREAD

**Issue by purpleidea** [howeyc/gopass#42]
There should be some way to unblock a blocked `GetPasswd` call if you'd like to stop waiting for user input after a certain timeout for example.

Common ways might be to allow passing in a context or to offer a `Cancel()` method somehow.

It might be best to add a `GetPasswdWithContext` function which adds the `context` param as input.

The only thing I'm unsure about is how the interruptability of waiting on stdin might work.

Thanks!

**Comment by purpleidea** [comment]
BTW, I'm happy to write the patch if someone can give me a pointer on the correct way to actually achieve this in terms of causing `getch` to unblock, eg: https://github.com/howeyc/gopass/blob/bf9dde6d0d2c004a008c27aaee91170c786f6db8/pass.go#L17

**Comment by purpleidea** [comment]
Would a https://golang.org/pkg/io/#ReadCloser help here?

**Comment by purpleidea** [comment]
A tip from golang IRC suggested that https://golang.org/pkg/os/#File.SetReadDeadline *could possibly* help here on `os.Stdin`.

**Comment by howeyc** [comment]
No longer maintained.
