### ISSUE TITLE
Ctrl+C doesn't cancel

### ISSUE THREAD

**Issue by bobappleyard** [howeyc/gopass#7]
I was expecting Ctrl+C to cancel password entry, instead it does nothing at all.

**Comment by proglottis** [comment]
I started looking into this. On OSX Ctrl+C is returning 0x3 from getch (end of text in ASCII). So think this'd be pretty easy to fix but this library has no errors. So you would have to pick either return an empty slice or return whatever has been typed so far. I don't think either way is ideal.

**Comment by mattes** [comment]
+1

**Comment by proglottis** [comment]
I made a [commit](https://github.com/proglottis/gopass/commit/b3d45d0f8680a43fd1762bbf8e5ea46f618fe5b4) to add errors to this interface.

It would be a breaking change though :disappointed:

**Comment by zerok** [comment]
Is this something that can even be handled through getch or should this perhaps be done using an signal listener? Does anyone of you know how Windows deals with things like that?

**Comment by johnSchnake** [comment]
So the way Windows deals with it depends on the console mode.  If the enable_process_input flag is set then the system aborts the program (like you would expect).  If it is not set, then the system does not handle it and byte 0x03 is read like on OSX.
